config/routes.rb
Rails.application.routes.draw do
  resources :categories

  root "events#index"

  get "events/filter/:filter" => "events#index", as: :filtered_events

  resources :events do
    resources :registrations
    resources :likes
  end
  resource :session, only: [:new, :create, :destroy]
  resources :users
  get "signup" => "users#new"
end

app/models/event.rb
class Event < ApplicationRecord
    
    before_save :set_slug

    has_many :registrations, dependent: :destroy #destroys the child/ren when parent is destroyed
    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user

    has_many :categorizations, dependent: :destroy
    has_many :categories, through: :categorizations

    has_one_attached :main_image
    #means the 2 rows below
    #has_one :main_image_attachment, dependent: :destroy
    #has_one :main_image_blob, through: :main_image_attachment

    validates :name, presence: true, uniqueness: true
    
    validates :location, presence: true
    
    validates :description, length: { minimum: 25 }
    
    validates :price, numericality: { greater_than_or_equal_to: 0 }
    
    validates :capacity, numericality:
                         { only_integer: true, greater_than: 0 }

    validate :acceptable_image

    scope :past, -> { where("starts_at < ?", Time.now).order("starts_at") }
    scope :upcoming, -> { where("starts_at > ?", Time.now).order("starts_at") }
    scope :free, -> { upcoming.where(price: 0.0).order(:name) }
    scope :recent, -> (max=3) { past.limit(max) }

    def free?
        price.blank? || price.zero? #price == 0
    end

    def sold_out?
        (capacity - registrations.size).zero?
    end

    def to_param
        slug
    end

private

    def set_slug
        self.slug = name.parameterize
    end

    def acceptable_image
        return unless main_image.attached?

        unless main_image.blob.byte_size <= 1.megabyte
            errors.add(:main_image, "is too big")
        end

        acceptable_types = ["image/jpeg", "image/png", "image/jpg"]
        unless acceptable_types.include?(main_image.content_type)
            errors.add(:main_image, "must be JPEG, JPG or PNG")
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    before_action :require_signin, except: [:index, :show]
    before_action :require_admin, except: [:index, :show]
    before_action :set_event, only: [:show, :edit, :update, :destroy]

    def index
        case params[:filter]
        when "past"
            @events = Event.past
        when "free"
            @events = Event.free
        when "recent"
            @events = Event.recent
        else
            @events = Event.upcoming
        end
    end

    def show
        @likers = @event.likers
        @categories = @event.categories
        if current_user
            @like = current_user.likes.find_by(event_id: @event.id)
        end
    end

    def edit

    end

    def update
        if @event.update(event_params)
            redirect_to @event, notice: "Event successfully updated!"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def new
        @event = Event.new
    end

    def create
        @event = Event.new(event_params)
        if @event.save
            redirect_to @event, notice: "Event successfully created!"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        @event.destroy
        redirect_to events_path, status: :see_other, notice: "Event successfully deleted!"
    end

private
    def set_event
        @event = Event.find_by!(slug: params[:id])
    end

    def event_params
        params.require(:event).
            permit(:name, :description, :price, :location, :starts_at, :main_image, :capacity, category_ids: [])
    end
end

app/helpers/events_helper.rb
module EventsHelper

    def price(event)
        if event.free?
            "Free"
        else
            number_to_currency(event.price, precision: 0)
        end
    end

    def date_and_time(event)
        event.starts_at.strftime("%B %d, %y at %I:%M %P")
    end

    def main_image(event)
        if event.main_image.attached?
            image_tag event.main_image
        else
            image_tag "placeholder.png"
        end
    end

    def nav_link_to(text, url)
        if current_page?(url)
            link_to(text, url, class: "navLink link active")
        else
            link_to(text, url, class: "navLink link")
        end
    end
    def mobile_nav_link_to(text, url)
        if current_page?(url)
            link_to(text, url, class: "navMobile active")
        else
            link_to(text, url, class: "navMobile")
        end
    end
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |f| %>

    <%= render "shared/errors", object: event %>

    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 5 %>

    <%= f.label :location %>
    <%= f.text_field :location %>

    <%= f.label :price %>
    <%= f.number_field :price %>

    <%= f.label :starts_at %>
    <%= f.datetime_select :starts_at, {ampm: true}, {class: "datetime"} %>

    <%= f.label :capacity %>
    <%= f.number_field :capacity %>

    <%= f.label :main_image %>
    <%= f.file_field :main_image %>

    <div class="checkboxes">
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
    </div>

    <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<div class="innerPage">
    
    <h2>Edit Event</h2>
    <div class="flex flex-col space-y-2">
        <%= render "form", event: @event %>
        <div><%= link_to "Cancel", event_path, class: "buton outlined block max-w-xl"%></div>
    </div>

</div>

app/views/events/index.html.erb
<div class="innerPage">
    <% @events.each do | event | %>
        <section class="eventListCard">
            <div class="eventLeft">
                <div class="image">
                    <%= main_image(event) %>
                </div>
            </div>
            <div class="eventRight">
                <div class="eventNameDatePrice">
                    <div class="md:grow">
                        <h2 class=""><%= link_to event.name, event %></h2>
                        <h4 class=""><span class=""><%= date_and_time(event) %> in <%= event.location%></span></h4>
                    </div>
                    <div class="eventPrice">
                        <span class="">
                            <%= price(event) %>
                        </span>
                    </div>
                </div>
                <div class="eventDescription">
                    <p>
                        <%= truncate(event.description, length: 35, separator: ' ') %>
                    </p>
                </div>
            </div>
        </section>
    <% end %>

    <% if current_user_admin? %>
        <section class="admin">
            <%= link_to "Add New Event", new_event_path, class: "button" %>
        </section>
    <% end %>
</div>

app/views/events/new.html.erb
<h1>Add New Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<div class="innerPage">
    <nav class="breadcrumb" aria-label="Breadcrumb">
        <ol class="">
            <li class="">
                <%= link_to "Events", events_path, class: ""%>
            </li>
            <li>
                <svg class="w-4 h-4 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 3l7 7-7 7-1.414-1.414L12.586 10H1V9h11.586L8.586 4.414z"/>
                </svg>
            </li>
            <li aria-current="page" class=""><%= @event.name%></li>
        </ol>
    </nav>

    <section class="eventListCard">
        <div class="eventLeft">
            <div class="image">
                <%= main_image(@event) %>
            </div>
            <div class="max-md:hidden">
                <% if current_user %>
                    <div class="likeAndCounter-desktop-only">
                        <div class="like"><%= like_or_unlike_button(@event, @like) %></div>
                        <div class="counter"><%= @likers.count %></div>
                    </div>
                <% end %>
            </div>
            <div class="likesAndCats-desktop-only">
                <% if @likers.present? %>
                    <header class="">Liked by</header>
                    <ul>
                        <% @likers.each do |user| %>
                            <li><%= link_to user.name, user %></li>
                        <% end %>
                    </ul>
                <% end %>

                <% if @categories.present? %>
                    <header>Categories</header>
                    <ul>
                        <% @categories.each do |c| %>
                            <li><%= link_to c.name, c %></li>
                        <% end %>
                    </ul>
                <% end %>
            </div>
        </div>

        <div class="eventRight">
            <div class="eventNameDatePrice">
                <div><h1><%= @event.name %></h1></div>
                <div><h4><span><%= date_and_time(@event) %> in <%= @event.location %></span></h4></div>
                <div class="eventPrice">
                    <span class="">
                        <%= price(@event) %>
                    </span>
                </div>
                <div><h4><span><%= pluralize(@event.capacity, "spot") %> &bull; <%= no_of_registrations(@event) %></span></h4></div>
            </div>
               
            <div class="eventActions">
                <div class="lg:w-60 register"><%= register_or_sold_out_desktop(@event) %></div>
                <% if current_user_admin? %>
                        <%= link_to "Edit", edit_event_path(@event), class: "buton outlined lg:w-32 max-sm:hidden" %>
                        <%= link_to "Delete", @event, class: "buton outlined-danger lg:w-32 max-sm:hidden",
                                data: { turbo_method: :delete, turbo_confirm: "Really?!" } %>
                <% end %>
            </div>

            <div class="eventDescription">
                <p><%= @event.description %><p>
            </div>

            <div class="likesAndCats-mobile-only">
                <% if @likers.present? %>
                    <header class="">Liked by</header>
                    <ul>
                        <% @likers.each do |user| %>
                            <li><%= link_to user.name, user %></li>
                        <% end %>
                    </ul>
                <% end %>

                <% if @categories.present? %>
                    <header>Categories</header>
                    <ul>
                        <% @categories.each do |c| %>
                            <li><%= link_to c.name, c %></li>
                        <% end %>
                    </ul>
                <% end %>
            </div>

            <div class="actions-mobile-only">
                <% if current_user_admin? %>
                    <%= link_to "Edit", edit_event_path(@event), class: "buton outlined lg:w-32" %>
                    <%= link_to "Delete", @event, class: "buton outlined-danger lg:w-32",
                            data: { turbo_method: :delete, turbo_confirm: "Really?!" } %>
                <% end %>
            </div>
        </div>
    </section>


</div>
<div class="eventRegisterAndLike-mobile-only">
    <div class="likeAndCounter">
        <div class="like"><%= like_or_unlike_button(@event, @like) %></div>
        <div class="counter"><%= @likers.count %></div>
    </div>
    <div class="grow"><%= register_or_sold_out_mobile(@event) %></div>
</div>