config/routes.rb
Rails.application.routes.draw do
  resources :categories

  root "events#index"

  get "events/filter/:filter" => "events#index", as: :filtered_events

  resources :events do
    resources :registrations
    resources :likes
  end
  resource :session, only: [:new, :create, :destroy]
  resources :users
  get "signup" => "users#new"
end

app/models/category.rb
class Category < ApplicationRecord
    before_save :set_slug

    has_many :categorizations, dependent: :destroy
    has_many :events, through: :categorizations

    validates :name, presence: true, uniqueness: true

    def to_param
        slug
    end

private

    def set_slug
        self.slug = name.parameterize
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :require_signin

    def index
        @categories = Category.all.order("name")
    end

    def show
        @events = @category.events
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            redirect_to categories_path, notice: "Category successfully added!"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit

    end

    def update
        if @category.update(category_params)
            redirect_to categories_path, notice: "Category successfully updated!"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @category.destroy
        redirect_to categories_path, status: :see_other, notice: "Category successfully deleted!"
    end
private

    def category_params
        params.require(:category).
            permit(:name)
    end

    def set_category
        @category = Category.find_by!(slug: params[:id])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |f| %>

    <%= render "shared/errors", object: category %>

    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>

    <%= f.submit %>
<% end%>

app/views/categories/edit.html.erb
<h1>Editing <%= @category.name%> Category</h1>

<%= render "form", category: @category %>

<%= link_to "Cancel", categories_path, class: "btn btn-outline-primary", style: "width: 100%; max-width: 503px; margin-top: 8px" %>

app/views/categories/index.html.erb
<h1><%= pluralize(@categories.size, "Category")%></h1>

<% @categories.each do |c|%>
    <div style="padding: 12px 0">
        <h3><%= link_to c.name, c%></h3>
        <%= link_to "Edit", edit_category_path(c), class: "btn btn-outline-primary btn-sm" %>
        <%= link_to "Delete", category_path(c), class: "btn btn-outline-danger btn-sm",
                                data: { turbo_method: :delete, turbo_confirm: "Really?!" } %>
    </div>
<% end%>

<section class="admin">
    <%= link_to "Add New Category", new_category_path, class: "button" %>
</section>

app/views/categories/new.html.erb
<h1>Adding New Category</h1>

<%= render "form", category: @category %>

<%= link_to "Cancel", categories_path, class: "btn btn-outline-primary", style: "width: 100%; max-width: 503px; margin-top: 8px" %>

app/views/categories/show.html.erb
<section style="padding-bottom: 20px">
  <%= link_to "< Back", categories_path, class: "btn btn-outline-secondary btn-sm" %>
</section>

<h1><%= pluralize(@events.size, "Event") %> under <%= @category.name%> Category</h1>

<div>
    <% @events.each do |event| %>
        <div style="padding-bottom: 40px">
            <%= link_to main_image(event), event %>
            <h3><%= event.name %></h3>
        </div>
    <% end %>
</div>