config/routes.rb
Rails.application.routes.draw do
  resources :categories

  root "events#index"

  get "events/filter/:filter" => "events#index", as: :filtered_events

  resources :events do
    resources :registrations
    resources :likes
  end
  resource :session, only: [:new, :create, :destroy]
  resources :users
  get "signup" => "users#new"
end

app/views/layouts/_flash.html.erb
<% if flash[:notice]%>
    <div class="flash notice">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert]%>
    <div class="flash alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <p>
        Made with ❤️ by <a href="https://derrickloo.design" >Derrick</a>
    </p>
    <a href="https://twitter.com/veggeloo?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-size="large" data-show-count="false">Follow @veggeloo</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</footer>

app/views/layouts/_header.html.erb
<header class="p-0 sticky top-0 z-40 lg:static" data-controller="navbar" data-action="resize@window->navbar#closeOnBigScreen keyup@window->navbar#closeWithKeyboard">
    <nav class="px-4 py-3 bg-blue-600 lg:p-6 flex flex-row justify-between items-center">
        <%= link_to image_tag("logo.png"), root_path %>
        <div class="max-lg:hidden grow">
            <ul class="space-x-2">
                <li><%= nav_link_to "Upcoming", events_path%></li>
                <li><%= nav_link_to "Past", filtered_events_path(:past)%></li>
                <li><%= nav_link_to "Free", filtered_events_path(:free)%></li>
                <li><%= nav_link_to "Recent", filtered_events_path(:recent) %></li>
            </ul>
        </div>
        <div class="max-lg:hidden grow">
            <ul class="justify-end space-x-2">
                <% if current_user %>
                    <li><%= nav_link_to current_user.name, current_user %></li>
                    <li><%= link_to "Sign Out", session_path, class: "buton outlined-inverse",
                                data: { turbo_method: :delete } %></li>
                <% else %>
                    <li><%= link_to "Sign In", new_session_path, class: "buton outlined-inverse" %></li> 
                    <li><%= link_to "Sign Up", signup_path, class: "buton pri-inverse" %></li> 
                <% end %>
            </ul>
        </div>
        <div class="lg:hidden text-2xl text-amber-50" role="button" data-action="click->navbar#toggle">
            &#9776;
        </div>
    </nav>
    
    <nav class="hidden p-4 bg-blue-800 absolute w-full overflow-y-auto" data-navbar-target="content">
        <div class="flex flex-col w-full divide-y divide-dashed divide-blue-600 space-y-2">
            <div class="">
                <ul class="flex flex-col">
                    <li class="m-0"><%= mobile_nav_link_to "Upcoming", events_path%></li>
                    <li class="m-0"><%= mobile_nav_link_to "Past", filtered_events_path(:past)%></li>
                    <li class="m-0"><%= mobile_nav_link_to "Free", filtered_events_path(:free)%></li>
                    <li class="m-0"><%= mobile_nav_link_to "Recent", filtered_events_path(:recent) %></li>
                </ul>
            </div>
            <div class="pt-2">
                <ul class="flex flex-col">
                    <% if current_user %>
                        <li><%= mobile_nav_link_to current_user.name, current_user %></li>
                        <li><%= link_to "Sign Out", session_path, class: "navMobile",
                                    data: { turbo_method: :delete } %></li>
                    <% else %>
                        <li><%= link_to "Sign In", new_session_path, class: "navMobile" %></li> 
                        <li><%= link_to "Sign Up", signup_path, class: "navMobile" %></li> 
                    <% end %>
                </ul>
            </div>
            <%#= h-[calc(50vh-56px)] %>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-amber-50">
    <%= render "layouts/header" %>
    <div id="modal-overlay" class="modal-overlay" style="display:none;"></div>
    
    <%#div class="content"%>
    <main class="md:grid grid-cols-8 gap-4">
      <div class="px-0 md:col-start-2 md:col-span-6">
        <%= render "layouts/flash" %>
        <%= yield %>
      </div>
    </main>

    <%= render "layouts/footer" %> 
  </body>
</html>